[package]
name = "tdcaster3"
version = "0.1.0"
authors = ["regenerativep <regeneralp@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
olc_pixel_game_engine = "0.5.0"
rand = "0.7.3"
rayon = "1.4.0"